[package]
name = "sort_bench"
version = "0.1.0"
edition = "2021"

[profile.bench]
opt-level = 3

[dependencies]
cubecl = { path = "../cubecl/crates/cubecl", features = ["wgpu"] }
tokio = { version = "1.43.0", features = ["full"] }
# tokio-macros = "2.4.0"
